3/30 chapter1_bmi
NackUn/FastCampusStudy pull request #6
Opened 2021-03-31 13:57 UTC by Dotton95

2021-03-31 14:49 UTC, NackUn commented
고생하셨습니다.

아래와 같이 수정하면 좋을 것들 남겨드립니다.

1. 다음과 같이 패키지 구조를 가지면 좋을 것 같습니다.
https://github.com/NackUn/FastCampusStudy/tree/developer/NackUn

2021-03-31 14:57 UTC, NackUn reviewed
고생하셨습니다.

리뷰를 달아봤는데 설명이 부족하거나 토론이 필요하면 말씀해주세요 ㅎㅎ

2021-03-31 14:57 UTC, NackUn commented on dotton95/chapter01_bmi/app/src/main/java/fastcampus/aop/part2/chapter1_bmi/DAO.kt
> +class DAO {
DAO 가 Data Access Object 역할을 하는거 맞나요?
안드로이드에서는 ViewModel 을 이용해서 데이터를 관리할 수 있습니다.
ViewModel을 상속받는 MainViewModel 클래스를 만들어서 사용하면 좋을 것 같습니다.
VIewModel을 이용해 MVVM 구조를 만들 수 있어요.
MVVM 구조를 배우기 전 MVP 구조를 만들어 보는 것도 좋다고 생각합니다^^

2021-03-31 14:57 UTC, NackUn commented on dotton95/chapter01_bmi/app/src/main/java/fastcampus/aop/part2/chapter1_bmi/DAO.kt
> +    val height = ObservableField<String>("")
ObservableField를 사용해보셨으면 LiveData도 사용해보는 것도 좋을 것 같아요^^

2021-03-31 14:57 UTC, NackUn commented on dotton95/chapter01_bmi/app/src/main/res/layout/activity_main.xml
> +            name="dao"
ViewModel을 사용하면 해당 variable에 ViewModel을 정의해줄 것이에요^^

2021-03-31 14:57 UTC, NackUn commented on dotton95/chapter01_bmi/app/src/main/java/fastcampus/aop/part2/chapter1_bmi/MainActivity.kt
> +    private lateinit var binding:ActivityMainBinding
이렇게 Activity에서 모든 Activity에서 사용하게 될 것들은 BaseActivity를 만들어서 사용하는 것도 좋은 방법이라고 생각합니다.

2021-04-19 12:55 UTC, Dotton95 commented
4/19 컨펌

2021-04-20 14:25 UTC, NackUn requested changes
고생하셨습니다.
MVVM 구조를 이해하시고 코드를 작성하고 계신 거 같아 좋습니다.
많이 사용하는 스타일에 대해서 리뷰해드립니다^^

2021-04-20 14:25 UTC, NackUn commented on dotton95/chapter01_bmi/app/src/main/AndroidManifest.xml
> +        <activity android:name=".ResultActivity"></activity>
/activity> 대신 />
로 사용하는건 어떠신가요?

2021-04-20 14:25 UTC, NackUn commented on dotton95/chapter01_bmi/app/src/main/AndroidManifest.xml
> +        <activity android:name=".BaseActivity"></activity>
BaseActivity는 Manifest에 따로 명시를 안해주셔도 될 것 같습니다 ㅎㅎ

2021-04-20 14:25 UTC, NackUn commented on dotton95/chapter01_bmi/app/src/main/java/fastcampus/aop/part2/chapter1_bmi/MainActivity.kt
> +
별거 아니지만 필요없는 개행인거 같습니다 ㅎㅎ

2021-04-20 14:25 UTC, NackUn commented on dotton95/chapter01_bmi/app/src/main/java/fastcampus/aop/part2/chapter1_bmi/MainActivity.kt
> +        }
1. (DI 없이) ViewModel을 엑티비티에서 사용하는 방법에 대해서 알아보시고 적용해보시면 좋을 것 같습니다.
2. 아래 두 가지 중 하나의 방식은 어떠세요?
* apply 말고 다른 범위지정 함수하기
* binding.setVariable(BR.vm, vm)

2021-04-20 14:25 UTC, NackUn commented on dotton95/chapter01_bmi/app/src/main/java/fastcampus/aop/part2/chapter1_bmi/ResultActivity.kt
>      var text:String? = null
데이터들은 ViewModel 이 들고 있는게 어떨까요?

2021-04-20 14:25 UTC, NackUn commented on dotton95/chapter01_bmi/app/src/main/java/fastcampus/aop/part2/chapter1_bmi/Vm.kt
> +class Vm() : ViewModel(){
ViewModel 을 하나 더 만드셔도 되고 SharedViewModel 로 사용을 해보셔도 좋을 것 같아요 ㅎㅎ

2021-04-22 12:46 UTC, closed without merging